### ISSUE TITLE
/stations endpoint retrieves no data

### ISSUE THREAD

**Issue by mho22** [iRail/iRail-docs#12] opened 2020-08-31 13:05 UTC
Trying to call the /stations endpoint results in version and timestamp element retrieving only.
No stations are returned. 

Documentation needs to be updated or endpoint should be repaired ?

**Comment by Bertware** [comment] 2020-08-31 15:12
This is a bug in iRail. Duplicate of https://github.com/iRail/iRail/issues/418

**Closed as completed by Bertware** 2020-08-31 15:12 UTC
Labels: duplicate
